#!/bin/bash

if [ -n "$INPUT_DEPENDENCIES" ]; then
    function install_dependencies {
        su - -c "apt-get install --no-install-recommends -y $INPUT_DEPENDENCIES"
    }
else
    function install_dependencies {
        :
    }
fi

CC="$INPUT_CC"
CXX="$INPUT_CC"
if [ "$CXX" = "gcc" ]; then
    CXX="g++"
elif [ "$CXX" = "clang" ]; then
    CXX="clang++"
fi

CFLAGS="$INPUT_CFLAGS"
CXXFLAGS="$INPUT_CXXFLAGS"
if [ -n "${INPUT_COVERAGE}" ]; then
    CFLAGS+=" --coverage"
    CXXFLAGS+=" --coverage"
fi

ctest=( ctest )
if [ -n "$INPUT_CTESTFLAGS" ]; then
    ctest+=( "$INPUT_CTESTFLAGS" )
fi

set -e -x

if [ -n "$INPUT_DIRECTORY" ]; then
    cd "$INPUT_DIRECTORY"
fi

if [ -n "$INPUT_ANALYZER" ]; then
    if [ "$INPUT_ANALYZER" = "clang-tidy" ]; then
        install_dependencies
        export CC="clang"
        export CXX="clang++"
        export CFLAGS="$CFLAGS"
        export CXXFLAGS="$CXXFLAGS"

        SRCDIR="$PWD"
        mkdir /tmp/_build /tmp/_install
        cd /tmp/_build
        conan install "$SRCDIR" --build=missing -s build_type=Release
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=/tmp/_install "$INPUT_CMAKEFLAGS" "$SRCDIR"

        clang++ --version
        find "$SRCDIR" \( -name '*.[ch]' -o -name '*.cc' -o -name '*.cpp' \) -exec clang-tidy -p "$PWD" {} +
        echo "Done." >&2
    elif [ "$INPUT_ANALYZER" = "clang-format" ]; then
        find "$PWD" \( -name '*.[ch]' -o -name '*.cc' -o -name '*.cpp' -o -name '*.hpp' \) -exec clang-format -i {} +
        # clang-format --dump-config
        git diff --exit-code
    else
        echo "Error: unknown analyzer $INPUT_ANALYZER" >&2
        exit 1
    fi
else
    install_dependencies
    export CC="$CC"
    export CXX="$CXX"
    export CFLAGS="$CFLAGS"
    export CXXFLAGS="$CXXFLAGS"

    SRCDIR="$PWD"
    mkdir /tmp/_build /tmp/_install
    cd /tmp/_build
    conan install "$SRCDIR" --build=missing -s build_type=Release
    cmake -DCMAKE_INSTALL_PREFIX=/tmp/_install "$INPUT_CMAKEFLAGS" "$SRCDIR"
    make VERBOSE=1
    "${ctest[@]}"
    make install

    if [ -n "${INPUT_COVERAGE}" ]; then
        if [ "$INPUT_COVERAGE" = codecov ]; then
            bash <(curl -s https://codecov.io/bash)
        else
            echo "Error: unknown coverage service $INPUT_COVERAGE" >&2
            exit 1
        fi
    fi
fi
